FROM node:20-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy source
COPY src ./src

# Expose port
EXPOSE 3001

# Start with dev mode
CMD ["npm", "run", "dev"]